(in-package :bloom)

(defun enable-logging (game-state)
  (let* ((error-file (resolve-path :log (option game-state :log-file-error)))
         (debug-file (resolve-path :log (option game-state :log-file-debug))))
    (uiop:ensure-all-directories-exist (list error-file debug-file))
    (unless (v:thread v:*global-controller*)
      (v:start v:*global-controller*))
    (setf v:*process-locally* (option game-state :release))
    (when (option game-state :log-repl-enable)
      (setf (v:repl-level) (if (option game-state :debug) :debug :info)
            (v:repl-categories) (option game-state :log-repl-categories)))
    (when (option game-state :log-file-enable)
      (v:define-pipe ()
        (v:level-filter :level :debug)
        (v:file-faucet :file debug-file))
      (v:define-pipe ()
        (v:level-filter :level :error)
        (v:file-faucet :file error-file)))))
